version: '3.8'

services:
  be-database:
    build:
      context: ../database/
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - be_database_data:/var/lib/postgresql/data
    networks:
      - backend-database-network

  be-tasks:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    networks:
      - backend-database-network
      - backend-network
    depends_on:
      - be-database

networks:
  backend-database-network:
    name: backend_database_network
    driver: bridge

volumes:
  be_database_data:
