version: '3.8'

services:
  be-database:
    build:
      context: ../database/
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gnammy
    volumes:
      - be_database_data:/var/lib/postgresql/data
    networks:
      - backend-database-network
    ports:
      - "5432:5432"

  be-gnammy:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - backend-database-network
    depends_on:
      - be-database

networks:
  backend-database-network:
    name: backend_database_network
    driver: bridge

volumes:
  be_database_data: