services:
  be-database:
    image: postgres
    restart: always
    build:
      context: ../database/
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gnammy
    volumes:
      - be_database_data:/var/lib/postgresql/data
    networks:
      - backend-database-network
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d gnammy -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "log_statement=all"]

  be-gnammy:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - backend-database-network
    depends_on:
      be-database:
        condition: service_healthy
    volumes:
      - ./../images/gnam:/usr/src/app/images/gnam
      - ./../images/user:/usr/src/app/images/user

networks:
  backend-database-network:

volumes:
  be_database_data:
